// surveyQuestions.js

const surveyQuestions = [
  "Survey ID",
  "Surveyor Name",
  "Date & Time",
  "District",
  "Taluka",
  "Village",
  "1. Name of the Farmer / Beneficiary",
  "2. Age years",
  "3. Gender",
  "4. Category",
  "5. Highest Education Level",
  "6. Phone Number",
  "7. Landholding Size",
  "8. Primary Occupation",
  "9. Secondary Occupation (if any)",
  "10. Total Agricultural Land Owned (in acre. Gunta)",
  "11. Irrigated Land (in acres. Gunta)",
  "12. Non-Irrigated Land (in acres, Gunta)",
  "13. Have you adopted micro irrigation? (Tick the appropriate option)",
  "If Drip",
  "If Sprinkler",
  "14. Have you taken Government subsidy for setting up Micro Irrigation?",
  "15. Which year you submitted your application?",
  "16. Month & Year of Installation",
  "17. Crop1 (Primary crop taken MI)",
  "Area1 (Acres, Gunta)",
  "Crop2",
  "Area2 (Acres, Gunta)",
  "Other Crop",
  "Other Area(Acres, Gunta)",
  "18. Source of Irrigation (tick applicable)",
  "19. How did you come to know about the PMKSY-PDMC Scheme?",
  "20. Who Installed the MI System?",
  "21. Name of the agency / vendor",
  "22. What are the MI components received? (tick applicable)",
  "23. Is the MI System Still in Use? If No, share the reason",
  "If No, mention the reason",
  "24. Did the MI agency or Government Department assist with the subsidy documentation? How was their response?",
  "25. Have you received the MI subsidy approval communication?",
  "26. How did you receive the communication? (tick applicable)",
  "27. Did the MI or Dept take your signature after successful installation?",
  "28. Have you received the MI subsidy payment approval message via SMS?",
  "29. Did you get any training or booklet on MI operation and maintenance? If yes, please give details",
  "30. Have you received any communication on MI System Warranty?",
  "31. Has the MI company provided any service after installation?",
  "32. Are you aware of the MI company’s service person, center, or helpline number? Please share details.",
  "33. When do you do the maintenance?",
  "34. Did you face any problems while using the MI system? If yes, please explain.",
  "35. Overall Satisfaction Level with MI System:",
  "36. Has your water use reduced after using the MI system? If yes, how much?",
  "37. Is there any reduction in labour cost per acre after using the MI system?",
  "Crop 1 ☐ Before MI ₹: ________ ☐After MI ₹: ________",
  "Crop 2 ☐ Before MI ₹: ________ ☐After MI ₹: ________",
  "38. Has the nutrition management cost per acre reduced after MI system use?",
  "☐ Before MI ₹: ________ ☐After MI ₹: ________",
  "39. Has the plant protection cost per acre reduced after MI system use?",
  "☐ Before MI ₹: ________ ☐After MI ₹: ________",
  "40. Has the crop yield per acre increased after adopting the MI system?",
  "☐ Before MI : ________ ☐After MI : ________",
  "41. Has your income per acre increased after adopting the MI system?",
  "☐ Before MI ₹: ________ ☐After MI ₹: ________",
  "42. MI Financial Details – Total cost of MI system installed (₹ per acre)",
  "43. MI Financial Details – Subsidy availed from the government (₹ per acre)",
  "44. Have you taken any loan from a financial institution for MI? If yes, from where and how much (₹)",
  "45. Has the adoption of MI influenced your standard of living?",
  "46. Did MI Adoption Create New Employment in Your Area?",
  "47. Has the adoption of MI helped in women empowerment?",
  "48. Has any member of your family been training on MI Maintenance?",
  "49. Have you observed any water saving after using the MI system? If yes, approx percentage reduction (%)",
  "50. Have you observed any change in groundwater levels after MI adoption?",
  "51. Would you recommend MI to other farmers under the current scheme?",
  "52. Any issues from Dept or MI agency during approval? If yes, list them",
  "53. Any Suggestions for Improving the MI Scheme?",
  "54. Any Additional comments?",
  "55. Have you attended any MI promotion activity organized by Government Departments? If yes, please provide the details.",
  "56. Farmer or Area Photo"
];

export default surveyQuestions;
